### ISSUE TITLE
Client as a separate project + react ?

### ISSUE THREAD

**Issue by znat** [howdyai/botkit-starter-web#1]
This is a really great and useful initiative.
I think it would be wise to make the client a separate project. Botkit suffers a bit from its lack of modularity and that would be a great starting point. Also, the client is a good candidate for React: affordances (quick replies, attachments,...) borrowed from Messenger can be complex and react handles that very well. In addition, long conversations could seriously impact the memory as it could have many hidden nodes. React has components to handle that in a similar way to view recycling in lists on native mobile sdk's

[Smooch](http://smooch.io) has full featured live web chat. [It's open source](https://github.com/smooch/smooch-js) but closely tight to their service. However, it shouldn't be that hard (easy to say, I know) to replace the link to Smooch with a simple socket connector.

**Comment by Naktibalda** [comment]
@znat smooth-js is open source, but it isn't a free software.
[LICENSE](https://github.com/smooch/smooch-js/blob/integration/LICENSE) file links to [T&C page](https://smooch.io/terms).
There is nothing about modification, but it is only allowed to use it for communication with Smooch platform.
https://smooch.io/terms/#licensesdk

**Comment by benbrown** [comment]
We could certainly think about separating the client out even further - but the current plan is for the client to live as part of this starter kit, while the actual server stuff lives in Botkit Core.

**Comment by CyrilPepito** [comment]
Hey @znat, 
I stumbled upon your issue while browsing Github, have you heard of [Broid](www.broid.ai)?
We offer a full featured (cards, carousel, quick replies, etc.) web messenger that you can plug with any other messaging apps like Slack or flowdock with our API.
Basically you can use Broid's API to converse on 20+ messaging channels (including that web messenger) using your favorite app to manager those conversations.
And it's free during our beta!

Also open source API here -> [Github repo](https://github.com/broidHQ/integrations)
