### ISSUE TITLE
How do I eliminate the say delay

### ISSUE THREAD

**Issue by jloveric** [howdyai/botkit-starter-web#13]
Hi, it seems there is a delay when the users presses "say" and when the bot actually responds.  How do I get rid of this?

**Comment by peterswimm** [comment]
Where are you hosting your bot?

**Comment by jloveric** [comment]
locally

**Comment by jloveric** [comment]
I verified that if I use the shellbot instead, it's much faster.

**Comment by gagan-bansal** [comment]
Its through Socket.js in botkit's branch [dev/webchannell](https://github.com/howdyai/botkit/tree/dev/webchannel) that is being used here.
Right now its based on the [typing length](https://github.com/howdyai/botkit/blob/93ad19f6c05fdc406b3fae7d2527ec00731efad7/lib/Sockets.js#L150) by  bot. You can manipulate in [Socket.js](https://github.com/howdyai/botkit/blob/93ad19f6c05fdc406b3fae7d2527ec00731efad7/lib/Sockets.js#L162)

**Comment by benbrown** [comment]
I have changed the behavior of this feature.

By default, there will be no delay.
You can turn on delay in a variety of ways:

* add `replyWithTyping: true` to your controller config
* use `bot.replyWithTyping` to send your reply instead of `bot.reply`
* set `message.typingDelay` to delay in ms
