### ISSUE TITLE
Inconsistent saving to database

### ISSUE THREAD

**Issue by jackdh** [howdyai/botkit-starter-web#15]
Hey, 

I've noticed some inconsistencies when it comes to the logs being saved to the data base. 

As you can see in the image below it's reached past the saving and yet it has not been updated in mongobd. I understand this is most likely due to it being asynchronous however it happens many times especially if you post an input and then refresh.

https://imgur.com/a/JlqHl

Any idea why this might be happening? My best bet is that the bot's reply is coming in directly after the user input (without the user inputs input in it's log) and then overwriting the user's input, thus removing it.

**Comment by Naktibalda** [comment]
a) You reported this issue in a wrong place - starter web has nothing to do with storage issues. MongoDb storage repo would be a better place.
b) storage works asynchronously, so your breakpoint is reached before storage did any work. If you want to inspect variables after storage has been updated, place breakpoint in the callback of save method.

**Comment by peterswimm** [comment]
Can you post this over here?

https://github.com/howdyai/botkit-storage-mongo

**Comment by jackdh** [comment]
I'm not too sure if this a botkit storage due to the storage mechanism working but how it is called from the web-starter side.

However if you also believe it is there issue I will take it over there.

For anyone else with this issue we managed a half fix for now but implementing small timeouts to simulate a network connection which has solved the issue.

**Comment by peterswimm** [comment]
@benbrown thoughts?

**Comment by Naktibalda** [comment]
Read, modify, store a whole thing process has an obvious race condition.
But again this isn't an issue of web starter site, it is a fundamental flaw of botkit storage.
It could be solved by some kind of locking mechanism, but I have no idea how to implement it in a node application which runs in a single process.

For logs it would be safer to use some kind of incremental storage, e.g. insert to database table or append to file.

**Comment by benbrown** [comment]
I'm not 100% clear on what the issue is here. Can you explain in more detail what the problem is @jackdh?

**Comment by jackdh** [comment]
As @Naktibalda summed up it's just a race condition problem.

There is just not enough time between saving and loading the database. In a production app this would probably never be a issue due to the delay, but locally it is.

**Comment by benbrown** [comment]
Ah, so like, you are missing messages because you are sending/receiving them so fast that they get overwritten in the history array?

This is a result of basically abusing the user object to handle the message history instead of providing a full db-backed solution.  In the future, we will likely go that direction.

**Comment by benbrown** [comment]
The original message history system has been deprecated in favor of a MongoDB backed plugin
