### ISSUE TITLE
Routes directory not included

### ISSUE THREAD

**Issue by devinakumar** [howdyai/botkit-starter-web#2]
I followed the instructions and kept getting an error (shown in the picture).  I added a "routes" directory in the appropriate place, and it seems to work now.

<img width="848" alt="screen shot 2017-06-20 at 9 55 22 am" src="https://user-images.githubusercontent.com/20134590/27345472-af759fc2-559e-11e7-917a-bbe0ddcb438e.png">

**Comment by benbrown** [comment]
This is fixed! Thanks for pointing it out.
