### ISSUE TITLE
Are there plans to make this server work with different storage providers?

### ISSUE THREAD

**Issue by pgoldweic** [howdyai/botkit-starter-web#23]
Are there plans to make botkit-starter-web work with alternative storage providers?  Since botkit itself does already allow this, I would have expected this feature to be supported here too, although it doesn't appear to be so currently. Is the feature in the roadmap?

**Comment by peterswimm** [comment]
No, if anything we plan to make this project more mongo specific in the future and will likely require a database to perform many of the upcoming features of the web starter.

**Comment by pgoldweic** [comment]
Ok, thanks for the info.

**Comment by peterswimm** [comment]
You can always modify the source here, or start with botkit core to make your own best implementation of this starter kit: https://github.com/howdyai/botkit/blob/master/docs/readme-web.md. If you have any questions, feel free to let us know!

**Comment by pgoldweic** [comment]
Hi @peterswimm, I'm still not clear as to whether the botkit storage API is still something that I can use within Botkit-anywhere (given that I wrote a limited message history functionality that depends on it). In particular, I'm using botkit-storage-dynamo as my storage provider, and I have written limited message history functionality using this storage api.  Could I simply avoid enabling the Mongo DB functionality and continue using my already existing message history functionality? (instead of having to re-work the new storage feature).  If so, how would I get my message history integrated into the GUI? 
Please advise. Thanks
