### ISSUE TITLE
not running in AWS server

### ISSUE THREAD

**Issue by swagat123** [howdyai/botkit-starter-web#28]
I was trying to run this in aws server. I have my IP <**.***.**.***>and port as 8085. I added the port in .env file.  In client.js  i changed the below code 
existing code - ws_url:(location.protocol === 'https:' ? 'wss' : 'ws') + '://' + loction.host,
changed code -  ws_url:(location.protocol === 'https:' ? 'wss' : 'ws') + '://0.0.0.0,
then run node bot.js and in chrome browser i added IP:8085 , only chat window is displayed with disconnected... reconnect and while never connected. Type any message also not sending. in browser it is showing  Not Secure | IP:8085
What went wrong? do I have to changed some where that it will work?

**Comment by Naktibalda** [comment]
I think that you had to leave that line of code as is if your backend is on the same server as frontend.

`0.0.0.0` is an odd choice of IP.
> In the context of servers, 0.0.0.0 can mean "all IPv4 addresses on the local machine"
So it is like localhost.

**Comment by swagat123** [comment]
yes , i revert back the changes and it is working now.
