### ISSUE TITLE
showing html text in replies

### ISSUE THREAD

**Issue by matteoredaelli** [howdyai/botkit-starter-web#3]
Hello

How could you render html texts in replies?

I would like to render properly links.. Using
    bot.reply(message, '<a href = "xx">test</a>');
it does not work ...

Regards
Matteo

**Comment by Naktibalda** [comment]
Change {{message.text}} to {{{message.text}}} in index.html

**Comment by migueltol22** [comment]
If no one has taken on this issue, I'd like to do that if possible

**Comment by peterswimm** [comment]
@migueltol22 did @Naktibalda suggestion not work for you?

**Comment by benbrown** [comment]
I included the showdown markdown renderer in the built in client.
now, message.text is run through the markdown renderer and sets `message.html`
the client now displays {{{message.html}}}!
