### ISSUE TITLE
How to install Botkit Anywhere?

### ISSUE THREAD

**Issue by nickppbd** [howdyai/botkit-starter-web#34]
Hi, I want to install Botkit Anywhere(Not Bokit core) after I got a good advice from @peterswimm ([link](https://github.com/howdyai/botkit/issues/1277))

I read some docs below.
https://botkit.ai/getstarted.html
https://github.com/howdyai/botkit-starter-web/blob/master/readme.md
https://github.com/howdyai/botkit/blob/master/readme.md

I will try https://botkit.ai/getstarted.html and start development.
But, I'm not sure this link is Botkit Anywhere.
Should I git https://github.com/howdyai/botkit-starter-web.git?

I have a qeustion about Botkit Studio.
Botkit Studio is free to use?

**Comment by adantoscano** [comment]
Hi buddy!

You can try here [https://glitch.com/~botkit-web](url) without deploy.

To deploy it, just clone the repo, `npm install` and `npm start`

Botkit studio got a free tier check this [https://botkit.groovehq.com/knowledge_base/topics/manage-your-billing-settings](url)

**Comment by nickppbd** [comment]
I got a question about installing botkit.

I just want to build a bokit application for web and app now, So I installed `git clone https://github.com/howdyai/botkit-starter-web.git` and `npm install` and `npm start`.

But, What if I extend my botkit application to facebook messanger?

This [docs](https://botkit.ai/docs/readme-facebook.html) says
`botkit new --platform facebook`

But, this command results in botkit: command not found

Every time I want to extend to another plaform, Should I use git clone?

But, I think Maybe It'll make another folder, so I should write new code which is the same as botkit-anywhere.

My logic is the same, But there are two codes.

What if I use `npm install -g botkit` for the first time when I install?
Is it different from `git clone https://github.com/howdyai/botkit-starter-web.git` and `npm install` and `npm start`?

And If I botkit new --platform facebook, It'll make another folder? so I should have two codes with the same logic?

**Comment by adantoscano** [comment]
To use `botkit new` you have to `npm install botkit -g` before.

Could be the same logic but facebook works with webhooks and have other triggers as 'facebook_postback' or 'facebook_optins' so you need two different controllers. Or create a new one could be awesome!

**Comment by benbrown** [comment]
@nickppbd right now, to have both a web bot and a Facebook bot, you will need to set up 2 separate apps.  These apps can share skills, but since the platforms are different, they have to be operated separately.

**Comment by nickppbd** [comment]
@adantoscano @benbrown 
Thank you all for great explanations. 
I don't know well 'facebook_options', but I surely understood that Logic could be different depending on platforms. I think it's a good idea that Making big conversation flow and using different functions for each platform.
To do this, Making conversation flow object and including sub-object for each platform in the flow object is pretty good idea, But it sounds like a dream. 
Anyway I really appreciate kind your answers. :)
