### ISSUE TITLE
Implement button template

### ISSUE THREAD

**Issue by mbruellmann** [howdyai/botkit-starter-web#42]
It would be nice to have the button template 
![grafik](https://user-images.githubusercontent.com/7466385/42825707-e18392f2-89e2-11e8-931c-f3c154da8fbb.png)
in the botkit's native chat service (as it is provided in the Botkit FB platforms.

**Comment by peterswimm** [comment]
Thats on the roadmap! Again its more of a Botkit Studio request but will put it on the roadmap.
