### ISSUE TITLE
Provide a direct link from script to console

### ISSUE THREAD

**Issue by mbruellmann** [howdyai/botkit-starter-web#43]
Please provide a link from "script" to the "console". I  find it often necessary to switch back and force between this two interfaces. 
![grafik](https://user-images.githubusercontent.com/7466385/42825977-9159f40a-89e3-11e8-825d-7fe10364b9cd.png)

**Comment by peterswimm** [comment]
This is not really a place to submit feature requests for Botkit Studio. but a fair idea. I often just grid a window with my bot code on glitch, the console on one table and the studio editor on another. ill add it to our internal list for consideration!

**Comment by peterswimm** [comment]
Yea, email is the best for now. help@botkit.ai
