### ISSUE TITLE
Invalid appsecret_proof provided in the API argument'  facebook api 

### ISSUE THREAD

**Issue by Abgaryan** [howdyai/botkit-starter-web#50]
I depolyed new vesrion of new bot and getting this error message 

info: An error occurred while sending a message: 
``{ message: 'Invalid appsecret_proof provided in the API argument',
type: 'GraphMethodException',
code: 100,}``

**Comment by Naktibalda** [comment]
It is better to raise Facebook specific issues in botkit repository.
