### ISSUE TITLE
How to build skills documentation with faulty example

### ISSUE THREAD

**Issue by Andr3s4n** [howdyai/botkit-starter-web#54]
In this readme file [How to build custom skill modules for Botkit](https://github.com/howdyai/botkit-starter-web/blob/master/docs/how_to_build_skills.md), the example code crashes:
```javascript
controller.hears('help', function(bot, message) {
  bot.reply(message, 'Need help? I am here!');
});
```
It should be fixed with:
```javascript
controller.hears('help', 'message_received', function(bot, message) {
  bot.reply(message, 'Need help? I am here!');
});
```

**Comment by Naktibalda** [comment]
Please edit the file and raise a pull request.

**Comment by benbrown** [comment]
good catch

**Comment by benbrown** [comment]
Fixed! Thank you.
