### ISSUE TITLE
React client?

### ISSUE THREAD

**Issue by voordev** [howdyai/botkit-starter-web#57]
Thank everyone for the efforts creating this.
Im looking for a resource to move from this client to a react based ui.
There are some react chat applications out there; could anyone of the team point me towards how I would move away from this client and hook to a react client?

I could not find anything so far about this.

**Comment by benbrown** [comment]
The included client is a very simple, vanilla javascript component that emits events.  You should be able to listen to those events and integrate with React. 

Alternatively, you could write a React component that interfaces directly with the websocket - it isn't too complex, as you will see in the client.js file.

**Comment by voordev** [comment]
Yes your right sorry to bother.

**Comment by Techwarriors2020** [comment]
> The included client is a very simple, vanilla javascript component that emits events. You should be able to listen to those events and integrate with React.
> 
> Alternatively, you could write a React component that interfaces directly with the websocket - it isn't too complex, as you will see in the client.js file.
could you please provide a sample for connection using react for the same?
