### ISSUE TITLE
Where do I get the token?

### ISSUE THREAD

**Issue by jloveric** [howdyai/botkit-starter-web#7]
Ok, so where do I get the token?  It's not obvious where on the botkit studio page.  I'm not interested in deploying the bot anywhere except just having a very simple web frontend (instead of the cli I'm using right now).  Also, what is the format of the .env file?

Thanks,

John

**Comment by peterswimm** [comment]
It can be found in your bot -> settings > api keys. You can view the env format on the glitch project:

https://botkit-web.glitch.me/

All of this will be documented better once this project is closer to public release.

**Comment by jloveric** [comment]
Thanks for the quick reply.  I realize I had to hit 'cancel' to see the setup options.
