### ISSUE TITLE
can't get rid of the default replies

### ISSUE THREAD

**Issue by jloveric** [howdyai/botkit-starter-web#8]
So I'm using the botkit web and I've deleted all the skills and replaced them with my own, but when I type 'Hi' I get all the old greet commands...  Anyway, I type 'Hi' and then the bot responds with

Hi!
Shalom!
You can edit it to customize my behaviors.

WHereas the only response should be "Hi" as that's the one I've programmed up.  Not sure where it is getting this other stuff from as grep hasn't yet shown anything.  Still looking.

**Comment by peterswimm** [comment]
Hello - Are you using botkit studio? There are default scripts in there as well that contain a hello example.

**Comment by jloveric** [comment]
I does include botkit in the dependencies inside the package.json
 
    "botkit": "git+https://git@github.com/howdyai/botkit.git#dev/webchannel",

**Comment by peterswimm** [comment]
Are you running your .env file with a token you created on a botkit studio account?

**Comment by jloveric** [comment]
Yes

**Comment by peterswimm** [comment]
Then you can go into your Studio account, edit the Hello script, and remove the other triggers, although we suggest you leave them be.

**Comment by benbrown** [comment]
@jloveric did this solve your problem?

**Comment by jloveric** [comment]
Yes, thanks.
